### ISSUE TITLE
Running `ceramic clay run web` on macos m1

### ISSUE THREAD

**Issue by 5u4** [ceramic-engine/ceramic#108]
Hi, I am walking through guide https://jeremyfa.com/getting-started-with-ceramic/ on a MacOS m1 machine. When I run `ceramic clay run web`, I am getting the following error. Do you have any idea how to fix this issue?

```
❯ ceramic clay run web
Will build with configuration Run for target web (Web).
Skip haxe compilation
Start ceramic runner
Create http server (port: 49103)
Load shader textured.vert textured.frag /Users/senhung/ceramic/runtime/src/ceramic/ShaderAsset.hx:72
Load shader msdf.vert msdf.frag /Users/senhung/ceramic/runtime/src/ceramic/ShaderAsset.hx:72
Load shader pixelArt.vert pixelArt.frag /Users/senhung/ceramic/runtime/src/ceramic/ShaderAsset.hx:72
Request status was 404 / Not Found /Users/senhung/ceramic/git/clay/src/clay/web/WebIO.hx:102
Request status was 404 / Not Found /Users/senhung/ceramic/git/clay/src/clay/web/WebIO.hx:102
Request status was 404 / Not Found /Users/senhung/ceramic/git/clay/src/clay/web/WebIO.hx:102
Request status was 404 / Not Found /Users/senhung/ceramic/git/clay/src/clay/web/WebIO.hx:102
Request status was 404 / Not Found /Users/senhung/ceramic/git/clay/src/clay/web/WebIO.hx:102
Request status was 404 / Not Found /Users/senhung/ceramic/git/clay/src/clay/web/WebIO.hx:102
GL / Failed to compile shader: /Users/senhung/ceramic/git/clay/src/clay/opengl/GLGraphics.hx:772
[error] /Users/senhung/ceramic/git/clay/src/clay/opengl/GLGraphics.hx:773
        // start -- (vert) compile log --
                ERROR: 1:1: '' : syntax error

        // end --

backend_ClayEvents.tick /Users/senhung/Desktop/rpsc/project/web/rpsc.js:10288:16
backend_Backend.emitUpdate /Users/senhung/Desktop/rpsc/project/web/rpsc.js:9946:5
ceramic_App.updatePreReady /Users/senhung/Desktop/rpsc/project/web/rpsc.js:21700:18
Function.ceramic_Assets.flushAllInstancesImmediate /Users/senhung/Desktop/rpsc/project/web/rpsc.js:7387:21
ceramic_Immediate.flush /Users/senhung/Desktop/rpsc/project/web/rpsc.js:34377:5
fn /Users/senhung/Desktop/rpsc/project/web/rpsc.js:15672:5
at /Users/senhung/Desktop/rpsc/project/web/rpsc.js:51589:12
backend_ShaderImpl.init /Users/senhung/Desktop/rpsc/project/web/rpsc.js:15219:25
Function.haxe_Exception.thrown /Users/senhung/Desktop/rpsc/project/web/rpsc.js:69813:11
at new haxe_ValueException (/Users/senhung/Desktop/rpsc/project/web/rpsc.js:70602:17)
Error: Failed to create shader (id=null)
```

**Comment by 5u4** [comment]
I found the issue. I need to run `ceramic clay run web --setup --assets` with CLI.
